# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "changelog.md"]
markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: innoMAYtion
subtitle: 'We are inclusive. We are innovative. We are Washington, DC.'

# Author/Organization info to be displayed in the templates
author:
  name: "Office of the Deputy Mayor for Planning & Economic Development"
  url: http://dmped.dc.gov

# When using this template with a project (repository) page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
baseurl: '/innoMAYtion'

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: '/assets/img/we-are-wdc.png'
logoalt: We Are Washington DC

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Events
  internal: true
  url: events.html


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: innoMAYtion
  description:
  url: https://github.com/DCgov/innoMAYtion

# google_analytics_ua: 

# Style Variables
brand_color: "#BF0000"
